packages:
  # Include all of the core configuration
  core: !include wordclock-esp8266-d1-mini.yaml

esphome:
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: clemensTyp.WordClock
    version: dev # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://clemenstyp/wordclock/wordclock-esp8266-d1-mini.yaml@main


# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:


text_sensor:
  - platform: template
    name: "Software Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    web_server: { sorting_weight: 12, sorting_group_id: "sorting_group_update" }   
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: template
    name: "Software Project Name"
    id: esphome_project_name
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    web_server: { sorting_weight: 11, sorting_group_id: "sorting_group_update" }   
    lambda: |-
      return { ESPHOME_PROJECT_NAME };

