packages:
  # Include all of the core configuration
  core: !include
    file: wordclock-core.yaml
    vars:
      devicename: wordclock
      friendly_name: "WordClock"
      fallback_hotspot_ssid: "WordClock"
      fallback_hotspot_password: "47110815"

  wordclock: !include
    file: wordclock.yaml
    vars:
      led_pin: D3
      i2c_scl_pin: D1
      i2c_sda_pin: D2



esp8266:
  board: d1_mini
  restore_from_flash: true

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

ota:
  - platform: http_request

# Enable logging
logger:
  level: INFO

update:
  - platform: http_request
    id: firmware_update
    name: Firmware
    source: https://clemenstyp.github.io/wordclock/firmware/wordclock.manifest.json
    update_interval: 6h
    icon: "mdi:cellphone-arrow-down"
    web_server: { sorting_weight: 30, sorting_group_id: "sorting_group_update" }
  - platform: http_request
    id: firmware_update_beta
    name: Firmware (Beta)
    source: https://clemenstyp.github.io/wordclock/beta-firmware/wordclock.manifest.json
    update_interval: 6h
    icon: "mdi:test-tube"
    disabled_by_default: true
    web_server: { sorting_weight: 32, sorting_group_id: "sorting_group_update" }

button:
  - platform: template
    name: "Install Beta Firmware"
    id: install_firmware_update_beta
    web_server: { sorting_weight: 36, sorting_group_id: "sorting_group_update" }
    icon: "mdi:test-tube"
    disabled_by_default: true
    entity_category: config
    on_press:
      # - update.perform:
      #     id: firmware_update_beta
      #     force_update: true
      - ota.http_request.flash:
          md5_url: https://clemenstyp.github.io/wordclock/beta-firmware/wordclock-esp8266.ota.bin.md5
          url: https://clemenstyp.github.io/wordclock/beta-firmware/wordclock-esp8266.ota.bin
  - platform: template
    name: "Install Firmware"
    id: install_firmware_update
    web_server: { sorting_weight: 35, sorting_group_id: "sorting_group_update" }
    icon: "mdi:cellphone-arrow-down"
    disabled_by_default: true
    entity_category: config
    on_press:
      # - update.perform:
      #     id: firmware_update
      #     force_update: true
      - ota.http_request.flash:
          md5_url: https://clemenstyp.github.io/wordclock/firmware/wordclock-esp8266.ota.bin.md5
          url: https://clemenstyp.github.io/wordclock/firmware/wordclock-esp8266.ota.bin


sensor:
  - platform: uptime
    id: last_boot_time
    type: timestamp
    name: "Last Boot Time"
    internal: false
    disabled_by_default: false
    web_server: { sorting_weight: 21, sorting_group_id: "sorting_group_diagnostic" }   
  - platform: uptime
    id: uptime_sensor
    type: seconds
    name: Uptime Sensor
    update_interval: 60s
    internal: false
    disabled_by_default: false
    web_server: { sorting_weight: 22, sorting_group_id: "sorting_group_diagnostic" }



