# CHANGEME: Set these variable to your liking
title: WordClock
description: WordClock instalation powered by ESPHome and ESP Web Tools
theme: jekyll-theme-minimal
# # Theme: https://github.com/pages-themes/minimal