name: Publish Dev Firmware

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.4.0
    with:
      #### Modify below here to match your project ####
      files: |
        wordclock-esp8266-d1-mini.dev.yaml
      esphome-version: stable
      combined-name: wordclock
      #### Modify above here to match your project ####

  upload-to-release:
    name: Upload to Release
    needs:
      - build-firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete old Dev-Releases
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            // Wrap the logic in an async function
            async function deleteOldDevReleases() {
              try {
                const repositoryTags = await github.rest.repos.listTags({
                  owner,
                  repo,
                });

                if (repositoryTags && repositoryTags.data) {
                  for (const tag of repositoryTags.data) {
                    if (tag.name.startsWith('dev-')) {
                      // Fetch the latest release information
                      const taggedRelease = await github.rest.repos.getReleaseByTag({
                        owner,
                        repo,
                        tag: tag.name,
                      });

                      // Check if the latest release information was successfully retrieved
                      if (taggedRelease && taggedRelease.data && taggedRelease.data.id) {
                        // If there is a latest release, then delete it
                        await github.rest.repos.deleteRelease({
                          owner,
                          repo,
                          release_id: taggedRelease.data.id,
                        });
                        console.log(`Release id ${taggedRelease.data.id} has been deleted.`);
                      } else {
                        // If no latest release was found or retrieval failed, output a message
                        console.log("No latest release found or failed to retrieve it.");
                      }
                    }
                  }
                }
              } catch (error) {
                console.error(`Failed to retrieve or delete release: ${error}`);
              }
            }

            // Call the async function
            deleteOldDevReleases();
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          path: files
      - name: Copy files to output
        run: |-
          shopt -s nullglob
          mkdir output
          version="${{ needs.build-firmware.outputs.version }}"
          pushd files
          for device in *; do
            pushd $device
            pushd $version
            cp manifest.json ../../../output/$device.manifest.json
            for bin in *.{bin,elf}; do
              md5sum $bin | head -c 32 > ../../../output/$bin.md5
              cp $bin ../../../output/
            done
            popd
            popd
          done
          popd
      - name: Generate Changelog
        run: |
          last_version=$(git tag --sort=taggerdate | grep -v '^dev-'  | head -n 1)
          echo "## Installation" > ${{ github.workspace }}-CHANGELOG.txt
          echo "[Beta Install Page](https://clemenstyp.github.io/wordclock/beta.html)" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "" >> ${{ github.workspace }}-CHANGELOG.txt

          echo "## Changes since version ${last_version}" > ${{ github.workspace }}-CHANGELOG.txt
          git log ${last_version}..HEAD --pretty=format:"%h" | while IFS= read -r hash
          do
              commit_message=$(git log -1 --pretty=format:"%B" $hash)
              echo "- $hash"
              echo "$commit_message" | sed 's/^/- /' >> ${{ github.workspace }}-CHANGELOG.txt
          done
      - name: Upload files to release
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: output/*
          tag_name: ${{ needs.build-firmware.outputs.version }}
          prerelease: true
          name: "Development Version: ${{ needs.build-firmware.outputs.version }}"
          body_path: ${{ github.workspace }}-CHANGELOG.txt