name: Publish Pages

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'
      - '.github/workflows/publish-pages.yml'
  workflow_run:
    workflows:
      - Publish Firmware
    types:
      - completed
  pull_request:
    paths:
      - 'static/**'
      - '.github/workflows/publish-pages.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - run: mkdir -p output/firmware

      - name: Build
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Get version tags
        id: version_tags
        run: |
          last_version_tag=$(git rev-list --tags --no-walk | xargs -I {} sh -c 'git tag --contains {} '| grep -E '^[0-9]'  | head -n 1)
          last_dev_version_tag=$(git rev-list --tags --no-walk | xargs -I {} sh -c 'git tag --contains {} '| grep  '^dev-'  | head -n 1)
          echo last_version_tag=$last_version_tag
          echo last_dev_version_tag=$last_dev_version_tag

          echo last_version_tag=$last_version_tag >> $GITHUB_OUTPUT
          echo last_dev_version_tag=$last_dev_version_tag >> $GITHUB_OUTPUT

      - name: Fetch firmware files
        if: ${{ steps.version_tags.outputs.last_version_tag != '' }}
        continue-on-error: true
        uses: robinraju/release-downloader@v1.12
        with:
          tag: ${{ steps.version_tags.outputs.last_version_tag }}
          fileName: '*'
          out-file-path: output/firmware

      - name: Fetch dev firmware files
        if: ${{ steps.version_tags.outputs.last_dev_version_tag != '' }}
        continue-on-error: true
        uses: robinraju/release-downloader@v1.12
        with:
          tag: ${{ steps.version_tags.outputs.last_dev_version_tag }}
          fileName: '*'
          out-file-path: output/beta-firmware

      - name: Upload artifact
        if: ${{ ! cancelled() }}
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: output
          retention-days: 1

  publish:
    if: github.event_name != 'pull_request'
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
